name: Update README with Recent Activity

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 30 minutes
  workflow_dispatch:        # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: readme-activity/readme-activity@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
